/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl;


import com.ftpix.mmath.dsl.tables.Events;
import com.ftpix.mmath.dsl.tables.Fighters;
import com.ftpix.mmath.dsl.tables.Fights;
import com.ftpix.mmath.dsl.tables.HypeTrains;
import com.ftpix.mmath.dsl.tables.HypeTrainsStats;
import com.ftpix.mmath.dsl.tables.Organizations;
import com.ftpix.mmath.dsl.tables.StatsCategories;
import com.ftpix.mmath.dsl.tables.StatsEntries;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>mmath</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENTS_PRIMARY = Indexes0.EVENTS_PRIMARY;
    public static final Index FIGHTERS_PRIMARY = Indexes0.FIGHTERS_PRIMARY;
    public static final Index FIGHTS_PRIMARY = Indexes0.FIGHTS_PRIMARY;
    public static final Index FIGHTS_PRIMARY_KEY = Indexes0.FIGHTS_PRIMARY_KEY;
    public static final Index HYPE_TRAINS_PRIMARY = Indexes0.HYPE_TRAINS_PRIMARY;
    public static final Index HYPE_TRAINS_STATS_PRIMARY = Indexes0.HYPE_TRAINS_STATS_PRIMARY;
    public static final Index ORGANIZATIONS_PRIMARY = Indexes0.ORGANIZATIONS_PRIMARY;
    public static final Index STATS_CATEGORIES_PRIMARY = Indexes0.STATS_CATEGORIES_PRIMARY;
    public static final Index STATS_ENTRIES_PRIMARY = Indexes0.STATS_ENTRIES_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EVENTS_PRIMARY = Internal.createIndex("PRIMARY", Events.EVENTS, new OrderField[] { Events.EVENTS.SHERDOGURL }, true);
        public static Index FIGHTERS_PRIMARY = Internal.createIndex("PRIMARY", Fighters.FIGHTERS, new OrderField[] { Fighters.FIGHTERS.SHERDOGURL }, true);
        public static Index FIGHTS_PRIMARY = Internal.createIndex("PRIMARY", Fights.FIGHTS, new OrderField[] { Fights.FIGHTS.ID }, true);
        public static Index FIGHTS_PRIMARY_KEY = Internal.createIndex("primary_key", Fights.FIGHTS, new OrderField[] { Fights.FIGHTS.FIGHTER1_ID, Fights.FIGHTS.FIGHTER2_ID, Fights.FIGHTS.EVENT_ID }, true);
        public static Index HYPE_TRAINS_PRIMARY = Internal.createIndex("PRIMARY", HypeTrains.HYPE_TRAINS, new OrderField[] { HypeTrains.HYPE_TRAINS.USER, HypeTrains.HYPE_TRAINS.FIGHTER }, true);
        public static Index HYPE_TRAINS_STATS_PRIMARY = Internal.createIndex("PRIMARY", HypeTrainsStats.HYPE_TRAINS_STATS, new OrderField[] { HypeTrainsStats.HYPE_TRAINS_STATS.MONTH, HypeTrainsStats.HYPE_TRAINS_STATS.FIGHTER }, true);
        public static Index ORGANIZATIONS_PRIMARY = Internal.createIndex("PRIMARY", Organizations.ORGANIZATIONS, new OrderField[] { Organizations.ORGANIZATIONS.SHERDOGURL }, true);
        public static Index STATS_CATEGORIES_PRIMARY = Internal.createIndex("PRIMARY", StatsCategories.STATS_CATEGORIES, new OrderField[] { StatsCategories.STATS_CATEGORIES.ID }, true);
        public static Index STATS_ENTRIES_PRIMARY = Internal.createIndex("PRIMARY", StatsEntries.STATS_ENTRIES, new OrderField[] { StatsEntries.STATS_ENTRIES.ID }, true);
    }
}
