/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl;


import com.ftpix.mmath.dsl.tables.Events;
import com.ftpix.mmath.dsl.tables.Fighters;
import com.ftpix.mmath.dsl.tables.Fights;
import com.ftpix.mmath.dsl.tables.HypeTrains;
import com.ftpix.mmath.dsl.tables.HypeTrainsStats;
import com.ftpix.mmath.dsl.tables.JdbcTest;
import com.ftpix.mmath.dsl.tables.Organizations;
import com.ftpix.mmath.dsl.tables.StatsCategories;
import com.ftpix.mmath.dsl.tables.StatsEntries;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mmath extends SchemaImpl {

    private static final long serialVersionUID = 545467365;

    /**
     * The reference instance of <code>mmath</code>
     */
    public static final Mmath MMATH = new Mmath();

    /**
     * The table <code>mmath.events</code>.
     */
    public final Events EVENTS = com.ftpix.mmath.dsl.tables.Events.EVENTS;

    /**
     * The table <code>mmath.fighters</code>.
     */
    public final Fighters FIGHTERS = com.ftpix.mmath.dsl.tables.Fighters.FIGHTERS;

    /**
     * The table <code>mmath.fights</code>.
     */
    public final Fights FIGHTS = com.ftpix.mmath.dsl.tables.Fights.FIGHTS;

    /**
     * The table <code>mmath.hype_trains</code>.
     */
    public final HypeTrains HYPE_TRAINS = com.ftpix.mmath.dsl.tables.HypeTrains.HYPE_TRAINS;

    /**
     * The table <code>mmath.hype_trains_stats</code>.
     */
    public final HypeTrainsStats HYPE_TRAINS_STATS = com.ftpix.mmath.dsl.tables.HypeTrainsStats.HYPE_TRAINS_STATS;

    /**
     * The table <code>mmath.jdbc_test</code>.
     */
    public final JdbcTest JDBC_TEST = com.ftpix.mmath.dsl.tables.JdbcTest.JDBC_TEST;

    /**
     * The table <code>mmath.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = com.ftpix.mmath.dsl.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>mmath.stats_categories</code>.
     */
    public final StatsCategories STATS_CATEGORIES = com.ftpix.mmath.dsl.tables.StatsCategories.STATS_CATEGORIES;

    /**
     * The table <code>mmath.stats_entries</code>.
     */
    public final StatsEntries STATS_ENTRIES = com.ftpix.mmath.dsl.tables.StatsEntries.STATS_ENTRIES;

    /**
     * No further instances allowed
     */
    private Mmath() {
        super("mmath", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Events.EVENTS,
            Fighters.FIGHTERS,
            Fights.FIGHTS,
            HypeTrains.HYPE_TRAINS,
            HypeTrainsStats.HYPE_TRAINS_STATS,
            JdbcTest.JDBC_TEST,
            Organizations.ORGANIZATIONS,
            StatsCategories.STATS_CATEGORIES,
            StatsEntries.STATS_ENTRIES);
    }
}
