/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl;


import com.ftpix.mmath.dsl.tables.Events;
import com.ftpix.mmath.dsl.tables.Fighters;
import com.ftpix.mmath.dsl.tables.Fights;
import com.ftpix.mmath.dsl.tables.FlywaySchemaHistory;
import com.ftpix.mmath.dsl.tables.HypeTrains;
import com.ftpix.mmath.dsl.tables.HypeTrainsStats;
import com.ftpix.mmath.dsl.tables.JdbcTest;
import com.ftpix.mmath.dsl.tables.Organizations;
import com.ftpix.mmath.dsl.tables.StatsCategories;
import com.ftpix.mmath.dsl.tables.StatsEntries;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mmath
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mmath.events</code>.
     */
    public static final Events EVENTS = com.ftpix.mmath.dsl.tables.Events.EVENTS;

    /**
     * The table <code>mmath.fighters</code>.
     */
    public static final Fighters FIGHTERS = com.ftpix.mmath.dsl.tables.Fighters.FIGHTERS;

    /**
     * The table <code>mmath.fights</code>.
     */
    public static final Fights FIGHTS = com.ftpix.mmath.dsl.tables.Fights.FIGHTS;

    /**
     * The table <code>mmath.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.ftpix.mmath.dsl.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>mmath.hype_trains</code>.
     */
    public static final HypeTrains HYPE_TRAINS = com.ftpix.mmath.dsl.tables.HypeTrains.HYPE_TRAINS;

    /**
     * The table <code>mmath.hype_trains_stats</code>.
     */
    public static final HypeTrainsStats HYPE_TRAINS_STATS = com.ftpix.mmath.dsl.tables.HypeTrainsStats.HYPE_TRAINS_STATS;

    /**
     * The table <code>mmath.jdbc_test</code>.
     */
    public static final JdbcTest JDBC_TEST = com.ftpix.mmath.dsl.tables.JdbcTest.JDBC_TEST;

    /**
     * The table <code>mmath.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = com.ftpix.mmath.dsl.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>mmath.stats_categories</code>.
     */
    public static final StatsCategories STATS_CATEGORIES = com.ftpix.mmath.dsl.tables.StatsCategories.STATS_CATEGORIES;

    /**
     * The table <code>mmath.stats_entries</code>.
     */
    public static final StatsEntries STATS_ENTRIES = com.ftpix.mmath.dsl.tables.StatsEntries.STATS_ENTRIES;
}
