kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./m2
        - ./src/main/web/node_modules

  - name: build web
    image: node:16
    commands:
      - cd mmath-web/src/main/web
      - npm install
      - npm run build

  - name: build hypetrain web
    image: node:16
    commands:
      - cd mmath-web/src/main/web
      - npm install
      - npm run build
      -
  - name: build backend
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean install -Dmaven.repo.local=./m2

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./m2
        - ./src/main/web/node_modules

#  - name: publish new version
#    image: plugins/docker
#    settings:
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
#      tags:
#        - '${DRONE_COMMIT}'
#        - '${DRONE_TAG}'
#        - latest
#      repo: gonzague/spendspentspent
#      context: ./
#      dockerfile: docker/Dockerfile.lite
#    when:
#      event: tag
#
#  - name: publish commit
#    image: plugins/docker
#    settings:
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
#      tags:
#        - '${DRONE_COMMIT}'
#      repo: gonzague/spendspentspent
#      context: ./
#      dockerfile: docker/Dockerfile.lite
#    when:
#      event:
#        exclude:
#          - tag
trigger:
  event:
    - push
    - tag

volumes:
  - name: cache
    host:
      path: /tmp/cache
