kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./m2
        - ./src/main/web/node_modules

  - name: build web
    image: node:16
    commands:
      - cd mmath-web/src/main/web
      - npm install
      - npm run build

  - name: build hypetrain web
    image: node:16
    commands:
      - cd mmath-web/src/main/web
      - npm install
      - npm run build
      -
  - name: build backend
    image: maven:3.8-openjdk-11
    commands:
      - mvn clean install -Dmaven.repo.local=./m2

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./m2
        - ./src/main/web/node_modules

  - name: publish mmath-cron
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/mmath-cron
      context: ./mmath-cron
      dockerfile: ./mmath-cron/Dockerfile
    when:
      event: tag

  - name: publish mmath-cron commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/mmath-cron
      context: ./mmath-cron
      dockerfile: ./mmath-cron/Dockerfile

  - name: publish mmath-crawler
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/mmath-crawler
      context: ./mmath-crawler-slave
      dockerfile: ./mmath-crawler-slave/Dockerfile
    when:
      event: tag

  - name: publish mmath-crawler commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/mmath-crawler
      context: ./mmath-crawler-slave
      dockerfile: ./mmath-crawler-slave/Dockerfile
    when:
      event:
        exclude:
          - tag

  - name: publish mmath-web
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/mmath-web
      context: ./mmath-web
      dockerfile: ./mmath-web/Dockerfile
    when:
      event: tag

  - name: publish mmath-web commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/mmath-web
      context: ./mmath-web
      dockerfile: ./mmath-web/Dockerfile
    when:
      event:
        exclude:
          - tag


  - name: publish hypetrain-web
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/hypetrain-web
      context: ./hypetrain-web
      dockerfile: ./hypetrain-web/Dockerfile
    when:
      event: tag

  - name: publish hypetrain-web commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/hypetrain-web
      context: ./hypetrain-web
      dockerfile: ./hypetrain-web/Dockerfile
    when:
      event:
        exclude:
          - tag

trigger:
  event:
    - push
    - tag

volumes:
  - name: cache
    host:
      path: /tmp/cache
