/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.Events;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record8<String, Timestamp, String, String, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = -1277897574;

    /**
     * Setter for <code>mmath.events.sherdogUrl</code>.
     */
    public void setSherdogurl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.events.sherdogUrl</code>.
     */
    public String getSherdogurl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mmath.events.date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.events.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>mmath.events.organization_id</code>.
     */
    public void setOrganizationId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mmath.events.organization_id</code>.
     */
    public String getOrganizationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mmath.events.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mmath.events.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mmath.events.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mmath.events.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mmath.events.lastUpdate</code>.
     */
    public void setLastupdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mmath.events.lastUpdate</code>.
     */
    public Timestamp getLastupdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mmath.events.contentHash</code>.
     */
    public void setContenthash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mmath.events.contentHash</code>.
     */
    public String getContenthash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mmath.events.lastContentCheck</code>.
     */
    public void setLastcontentcheck(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mmath.events.lastContentCheck</code>.
     */
    public Timestamp getLastcontentcheck() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Timestamp, String, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Timestamp, String, String, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Events.EVENTS.SHERDOGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Events.EVENTS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Events.EVENTS.ORGANIZATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Events.EVENTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Events.EVENTS.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Events.EVENTS.LASTUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Events.EVENTS.CONTENTHASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Events.EVENTS.LASTCONTENTCHECK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSherdogurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getContenthash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastcontentcheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSherdogurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getContenthash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastcontentcheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value1(String value) {
        setSherdogurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value3(String value) {
        setOrganizationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value5(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value6(Timestamp value) {
        setLastupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value7(String value) {
        setContenthash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value8(Timestamp value) {
        setLastcontentcheck(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord values(String value1, Timestamp value2, String value3, String value4, String value5, Timestamp value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(String sherdogurl, Timestamp date, String organizationId, String name, String location, Timestamp lastupdate, String contenthash, Timestamp lastcontentcheck) {
        super(Events.EVENTS);

        set(0, sherdogurl);
        set(1, date);
        set(2, organizationId);
        set(3, name);
        set(4, location);
        set(5, lastupdate);
        set(6, contenthash);
        set(7, lastcontentcheck);
    }
}
