/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.Fights;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FightsRecord extends UpdatableRecordImpl<FightsRecord> implements Record11<Long, String, String, String, Timestamp, String, String, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = 1615894843;

    /**
     * Setter for <code>mmath.fights.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.fights.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mmath.fights.fighter1_id</code>.
     */
    public void setFighter1Id(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.fights.fighter1_id</code>.
     */
    public String getFighter1Id() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mmath.fights.fighter2_id</code>.
     */
    public void setFighter2Id(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mmath.fights.fighter2_id</code>.
     */
    public String getFighter2Id() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mmath.fights.event_id</code>.
     */
    public void setEventId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mmath.fights.event_id</code>.
     */
    public String getEventId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mmath.fights.date</code>.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mmath.fights.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mmath.fights.result</code>.
     */
    public void setResult(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mmath.fights.result</code>.
     */
    public String getResult() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mmath.fights.winMethod</code>.
     */
    public void setWinmethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mmath.fights.winMethod</code>.
     */
    public String getWinmethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mmath.fights.winTime</code>.
     */
    public void setWintime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mmath.fights.winTime</code>.
     */
    public String getWintime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mmath.fights.winRound</code>.
     */
    public void setWinround(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mmath.fights.winRound</code>.
     */
    public Integer getWinround() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mmath.fights.lastUpdate</code>.
     */
    public void setLastupdate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mmath.fights.lastUpdate</code>.
     */
    public Timestamp getLastupdate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mmath.fights.fight_type</code>.
     */
    public void setFightType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mmath.fights.fight_type</code>.
     */
    public String getFightType() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, Timestamp, String, String, String, Integer, Timestamp, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, Timestamp, String, String, String, Integer, Timestamp, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Fights.FIGHTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Fights.FIGHTS.FIGHTER1_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Fights.FIGHTS.FIGHTER2_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Fights.FIGHTS.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Fights.FIGHTS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Fights.FIGHTS.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Fights.FIGHTS.WINMETHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Fights.FIGHTS.WINTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Fights.FIGHTS.WINROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Fights.FIGHTS.LASTUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Fights.FIGHTS.FIGHT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFighter1Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFighter2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWinmethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getWintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getWinround();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFightType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFighter1Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFighter2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWinmethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getWintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getWinround();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFightType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value2(String value) {
        setFighter1Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value3(String value) {
        setFighter2Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value4(String value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value6(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value7(String value) {
        setWinmethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value8(String value) {
        setWintime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value9(Integer value) {
        setWinround(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value10(Timestamp value) {
        setLastupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value11(String value) {
        setFightType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, String value6, String value7, String value8, Integer value9, Timestamp value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FightsRecord
     */
    public FightsRecord() {
        super(Fights.FIGHTS);
    }

    /**
     * Create a detached, initialised FightsRecord
     */
    public FightsRecord(Long id, String fighter1Id, String fighter2Id, String eventId, Timestamp date, String result, String winmethod, String wintime, Integer winround, Timestamp lastupdate, String fightType) {
        super(Fights.FIGHTS);

        set(0, id);
        set(1, fighter1Id);
        set(2, fighter2Id);
        set(3, eventId);
        set(4, date);
        set(5, result);
        set(6, winmethod);
        set(7, wintime);
        set(8, winround);
        set(9, lastupdate);
        set(10, fightType);
    }
}
