/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.Fighters;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FightersRecord extends UpdatableRecordImpl<FightersRecord> implements Record18<String, Timestamp, String, Date, Integer, Integer, Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1822711865;

    /**
     * Setter for <code>mmath.fighters.sherdogUrl</code>.
     */
    public void setSherdogurl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.fighters.sherdogUrl</code>.
     */
    public String getSherdogurl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mmath.fighters.lastUpdate</code>.
     */
    public void setLastupdate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.fighters.lastUpdate</code>.
     */
    public Timestamp getLastupdate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>mmath.fighters.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mmath.fighters.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mmath.fighters.birthday</code>.
     */
    public void setBirthday(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>mmath.fighters.birthday</code>.
     */
    public Date getBirthday() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>mmath.fighters.draws</code>.
     */
    public void setDraws(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mmath.fighters.draws</code>.
     */
    public Integer getDraws() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mmath.fighters.losses</code>.
     */
    public void setLosses(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mmath.fighters.losses</code>.
     */
    public Integer getLosses() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mmath.fighters.wins</code>.
     */
    public void setWins(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mmath.fighters.wins</code>.
     */
    public Integer getWins() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mmath.fighters.weight</code>.
     */
    public void setWeight(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mmath.fighters.weight</code>.
     */
    public String getWeight() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mmath.fighters.height</code>.
     */
    public void setHeight(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mmath.fighters.height</code>.
     */
    public String getHeight() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mmath.fighters.nickname</code>.
     */
    public void setNickname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mmath.fighters.nickname</code>.
     */
    public String getNickname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mmath.fighters.nc</code>.
     */
    public void setNc(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mmath.fighters.nc</code>.
     */
    public Integer getNc() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mmath.fighters.search_rank</code>.
     */
    public void setSearchRank(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>mmath.fighters.search_rank</code>.
     */
    public Integer getSearchRank() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>mmath.fighters.winKo</code>.
     */
    public void setWinko(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>mmath.fighters.winKo</code>.
     */
    public Integer getWinko() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>mmath.fighters.winSub</code>.
     */
    public void setWinsub(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>mmath.fighters.winSub</code>.
     */
    public Integer getWinsub() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>mmath.fighters.winDec</code>.
     */
    public void setWindec(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>mmath.fighters.winDec</code>.
     */
    public Integer getWindec() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>mmath.fighters.lossKo</code>.
     */
    public void setLossko(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>mmath.fighters.lossKo</code>.
     */
    public Integer getLossko() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>mmath.fighters.lossSub</code>.
     */
    public void setLosssub(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>mmath.fighters.lossSub</code>.
     */
    public Integer getLosssub() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>mmath.fighters.lossDec</code>.
     */
    public void setLossdec(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>mmath.fighters.lossDec</code>.
     */
    public Integer getLossdec() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, Timestamp, String, Date, Integer, Integer, Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, Timestamp, String, Date, Integer, Integer, Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Fighters.FIGHTERS.SHERDOGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Fighters.FIGHTERS.LASTUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Fighters.FIGHTERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Fighters.FIGHTERS.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Fighters.FIGHTERS.DRAWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Fighters.FIGHTERS.LOSSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Fighters.FIGHTERS.WINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Fighters.FIGHTERS.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Fighters.FIGHTERS.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Fighters.FIGHTERS.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Fighters.FIGHTERS.NC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Fighters.FIGHTERS.SEARCH_RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Fighters.FIGHTERS.WINKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Fighters.FIGHTERS.WINSUB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Fighters.FIGHTERS.WINDEC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return Fighters.FIGHTERS.LOSSKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Fighters.FIGHTERS.LOSSSUB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Fighters.FIGHTERS.LOSSDEC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSherdogurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDraws();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getLosses();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getWins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getNc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getSearchRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getWinko();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getWinsub();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getWindec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getLossko();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getLosssub();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getLossdec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSherdogurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDraws();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLosses();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getWins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getNc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getSearchRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getWinko();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getWinsub();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getWindec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getLossko();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getLosssub();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getLossdec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value1(String value) {
        setSherdogurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value2(Timestamp value) {
        setLastupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value4(Date value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value5(Integer value) {
        setDraws(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value6(Integer value) {
        setLosses(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value7(Integer value) {
        setWins(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value8(String value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value9(String value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value10(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value11(Integer value) {
        setNc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value12(Integer value) {
        setSearchRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value13(Integer value) {
        setWinko(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value14(Integer value) {
        setWinsub(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value15(Integer value) {
        setWindec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value16(Integer value) {
        setLossko(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value17(Integer value) {
        setLosssub(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord value18(Integer value) {
        setLossdec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightersRecord values(String value1, Timestamp value2, String value3, Date value4, Integer value5, Integer value6, Integer value7, String value8, String value9, String value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16, Integer value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FightersRecord
     */
    public FightersRecord() {
        super(Fighters.FIGHTERS);
    }

    /**
     * Create a detached, initialised FightersRecord
     */
    public FightersRecord(String sherdogurl, Timestamp lastupdate, String name, Date birthday, Integer draws, Integer losses, Integer wins, String weight, String height, String nickname, Integer nc, Integer searchRank, Integer winko, Integer winsub, Integer windec, Integer lossko, Integer losssub, Integer lossdec) {
        super(Fighters.FIGHTERS);

        set(0, sherdogurl);
        set(1, lastupdate);
        set(2, name);
        set(3, birthday);
        set(4, draws);
        set(5, losses);
        set(6, wins);
        set(7, weight);
        set(8, height);
        set(9, nickname);
        set(10, nc);
        set(11, searchRank);
        set(12, winko);
        set(13, winsub);
        set(14, windec);
        set(15, lossko);
        set(16, losssub);
        set(17, lossdec);
    }
}
