/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.HypeTrains;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypeTrainsRecord extends UpdatableRecordImpl<HypeTrainsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1891761147;

    /**
     * Setter for <code>mmath.hype_trains.user</code>.
     */
    public void setUser(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.hype_trains.user</code>.
     */
    public String getUser() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mmath.hype_trains.fighter</code>.
     */
    public void setFighter(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.hype_trains.fighter</code>.
     */
    public String getFighter() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return HypeTrains.HYPE_TRAINS.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HypeTrains.HYPE_TRAINS.FIGHTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFighter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFighter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsRecord value1(String value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsRecord value2(String value) {
        setFighter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HypeTrainsRecord
     */
    public HypeTrainsRecord() {
        super(HypeTrains.HYPE_TRAINS);
    }

    /**
     * Create a detached, initialised HypeTrainsRecord
     */
    public HypeTrainsRecord(String user, String fighter) {
        super(HypeTrains.HYPE_TRAINS);

        set(0, user);
        set(1, fighter);
    }
}
