/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.HypeTrainsStats;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypeTrainsStatsRecord extends UpdatableRecordImpl<HypeTrainsStatsRecord> implements Record3<String, String, Long> {

    private static final long serialVersionUID = 1743670938;

    /**
     * Setter for <code>mmath.hype_trains_stats.month</code>.
     */
    public void setMonth(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.hype_trains_stats.month</code>.
     */
    public String getMonth() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mmath.hype_trains_stats.fighter</code>.
     */
    public void setFighter(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.hype_trains_stats.fighter</code>.
     */
    public String getFighter() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mmath.hype_trains_stats.count</code>.
     */
    public void setCount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>mmath.hype_trains_stats.count</code>.
     */
    public Long getCount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return HypeTrainsStats.HYPE_TRAINS_STATS.MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HypeTrainsStats.HYPE_TRAINS_STATS.FIGHTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return HypeTrainsStats.HYPE_TRAINS_STATS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFighter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFighter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStatsRecord value1(String value) {
        setMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStatsRecord value2(String value) {
        setFighter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStatsRecord value3(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStatsRecord values(String value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HypeTrainsStatsRecord
     */
    public HypeTrainsStatsRecord() {
        super(HypeTrainsStats.HYPE_TRAINS_STATS);
    }

    /**
     * Create a detached, initialised HypeTrainsStatsRecord
     */
    public HypeTrainsStatsRecord(String month, String fighter, Long count) {
        super(HypeTrainsStats.HYPE_TRAINS_STATS);

        set(0, month);
        set(1, fighter);
        set(2, count);
    }
}
