/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.JdbcTest;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JdbcTestRecord extends TableRecordImpl<JdbcTestRecord> implements Record1<String> {

    private static final long serialVersionUID = -473688048;

    /**
     * Setter for <code>mmath.jdbc_test.a</code>.
     */
    public void setA(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.jdbc_test.a</code>.
     */
    public String getA() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JdbcTest.JDBC_TEST.A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JdbcTestRecord value1(String value) {
        setA(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JdbcTestRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JdbcTestRecord
     */
    public JdbcTestRecord() {
        super(JdbcTest.JDBC_TEST);
    }

    /**
     * Create a detached, initialised JdbcTestRecord
     */
    public JdbcTestRecord(String a) {
        super(JdbcTest.JDBC_TEST);

        set(0, a);
    }
}
