/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables.records;


import com.ftpix.mmath.dsl.tables.StatsEntries;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatsEntriesRecord extends UpdatableRecordImpl<StatsEntriesRecord> implements Record8<Integer, String, String, Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = -10668274;

    /**
     * Setter for <code>mmath.stats_entries.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mmath.stats_entries.category_id</code>.
     */
    public void setCategoryId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.category_id</code>.
     */
    public String getCategoryId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mmath.stats_entries.fighter_id</code>.
     */
    public void setFighterId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.fighter_id</code>.
     */
    public String getFighterId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mmath.stats_entries.percent</code>.
     */
    public void setPercent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.percent</code>.
     */
    public Integer getPercent() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mmath.stats_entries.rank</code>.
     */
    public void setRank(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mmath.stats_entries.text_to_show</code>.
     */
    public void setTextToShow(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.text_to_show</code>.
     */
    public String getTextToShow() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mmath.stats_entries.details</code>.
     */
    public void setDetails(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.details</code>.
     */
    public String getDetails() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mmath.stats_entries.lastUpdate</code>.
     */
    public void setLastupdate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mmath.stats_entries.lastUpdate</code>.
     */
    public Timestamp getLastupdate() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StatsEntries.STATS_ENTRIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StatsEntries.STATS_ENTRIES.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StatsEntries.STATS_ENTRIES.FIGHTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return StatsEntries.STATS_ENTRIES.PERCENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return StatsEntries.STATS_ENTRIES.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StatsEntries.STATS_ENTRIES.TEXT_TO_SHOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StatsEntries.STATS_ENTRIES.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return StatsEntries.STATS_ENTRIES.LASTUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFighterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPercent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTextToShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFighterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPercent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTextToShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value2(String value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value3(String value) {
        setFighterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value4(Integer value) {
        setPercent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value5(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value6(String value) {
        setTextToShow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value7(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord value8(Timestamp value) {
        setLastupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsEntriesRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatsEntriesRecord
     */
    public StatsEntriesRecord() {
        super(StatsEntries.STATS_ENTRIES);
    }

    /**
     * Create a detached, initialised StatsEntriesRecord
     */
    public StatsEntriesRecord(Integer id, String categoryId, String fighterId, Integer percent, Integer rank, String textToShow, String details, Timestamp lastupdate) {
        super(StatsEntries.STATS_ENTRIES);

        set(0, id);
        set(1, categoryId);
        set(2, fighterId);
        set(3, percent);
        set(4, rank);
        set(5, textToShow);
        set(6, details);
        set(7, lastupdate);
    }
}
