/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables;


import com.ftpix.mmath.dsl.Indexes;
import com.ftpix.mmath.dsl.Keys;
import com.ftpix.mmath.dsl.Mmath;
import com.ftpix.mmath.dsl.tables.records.HypeTrainsStatsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypeTrainsStats extends TableImpl<HypeTrainsStatsRecord> {

    private static final long serialVersionUID = -530200306;

    /**
     * The reference instance of <code>mmath.hype_trains_stats</code>
     */
    public static final HypeTrainsStats HYPE_TRAINS_STATS = new HypeTrainsStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HypeTrainsStatsRecord> getRecordType() {
        return HypeTrainsStatsRecord.class;
    }

    /**
     * The column <code>mmath.hype_trains_stats.month</code>.
     */
    public final TableField<HypeTrainsStatsRecord, String> MONTH = createField("month", org.jooq.impl.SQLDataType.VARCHAR(7).nullable(false), this, "");

    /**
     * The column <code>mmath.hype_trains_stats.fighter</code>.
     */
    public final TableField<HypeTrainsStatsRecord, String> FIGHTER = createField("fighter", org.jooq.impl.SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>mmath.hype_trains_stats.count</code>.
     */
    public final TableField<HypeTrainsStatsRecord, Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>mmath.hype_trains_stats</code> table reference
     */
    public HypeTrainsStats() {
        this(DSL.name("hype_trains_stats"), null);
    }

    /**
     * Create an aliased <code>mmath.hype_trains_stats</code> table reference
     */
    public HypeTrainsStats(String alias) {
        this(DSL.name(alias), HYPE_TRAINS_STATS);
    }

    /**
     * Create an aliased <code>mmath.hype_trains_stats</code> table reference
     */
    public HypeTrainsStats(Name alias) {
        this(alias, HYPE_TRAINS_STATS);
    }

    private HypeTrainsStats(Name alias, Table<HypeTrainsStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private HypeTrainsStats(Name alias, Table<HypeTrainsStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HypeTrainsStats(Table<O> child, ForeignKey<O, HypeTrainsStatsRecord> key) {
        super(child, key, HYPE_TRAINS_STATS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mmath.MMATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HYPE_TRAINS_STATS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HypeTrainsStatsRecord> getPrimaryKey() {
        return Keys.KEY_HYPE_TRAINS_STATS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HypeTrainsStatsRecord>> getKeys() {
        return Arrays.<UniqueKey<HypeTrainsStatsRecord>>asList(Keys.KEY_HYPE_TRAINS_STATS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStats as(String alias) {
        return new HypeTrainsStats(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypeTrainsStats as(Name alias) {
        return new HypeTrainsStats(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HypeTrainsStats rename(String name) {
        return new HypeTrainsStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HypeTrainsStats rename(Name name) {
        return new HypeTrainsStats(name, null);
    }
}
