/*
 * This file is generated by jOOQ.
 */
package com.ftpix.mmath.dsl.tables;


import com.ftpix.mmath.dsl.Indexes;
import com.ftpix.mmath.dsl.Keys;
import com.ftpix.mmath.dsl.Mmath;
import com.ftpix.mmath.dsl.tables.records.StatsCategoriesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatsCategories extends TableImpl<StatsCategoriesRecord> {

    private static final long serialVersionUID = -94319339;

    /**
     * The reference instance of <code>mmath.stats_categories</code>
     */
    public static final StatsCategories STATS_CATEGORIES = new StatsCategories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatsCategoriesRecord> getRecordType() {
        return StatsCategoriesRecord.class;
    }

    /**
     * The column <code>mmath.stats_categories.id</code>.
     */
    public final TableField<StatsCategoriesRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>mmath.stats_categories.name</code>.
     */
    public final TableField<StatsCategoriesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>mmath.stats_categories.description</code>.
     */
    public final TableField<StatsCategoriesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>mmath.stats_categories.order</code>.
     */
    public final TableField<StatsCategoriesRecord, Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mmath.stats_categories.lastUpdate</code>.
     */
    public final TableField<StatsCategoriesRecord, Timestamp> LASTUPDATE = createField("lastUpdate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mmath.stats_categories</code> table reference
     */
    public StatsCategories() {
        this(DSL.name("stats_categories"), null);
    }

    /**
     * Create an aliased <code>mmath.stats_categories</code> table reference
     */
    public StatsCategories(String alias) {
        this(DSL.name(alias), STATS_CATEGORIES);
    }

    /**
     * Create an aliased <code>mmath.stats_categories</code> table reference
     */
    public StatsCategories(Name alias) {
        this(alias, STATS_CATEGORIES);
    }

    private StatsCategories(Name alias, Table<StatsCategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatsCategories(Name alias, Table<StatsCategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> StatsCategories(Table<O> child, ForeignKey<O, StatsCategoriesRecord> key) {
        super(child, key, STATS_CATEGORIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mmath.MMATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STATS_CATEGORIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatsCategoriesRecord> getPrimaryKey() {
        return Keys.KEY_STATS_CATEGORIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatsCategoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<StatsCategoriesRecord>>asList(Keys.KEY_STATS_CATEGORIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsCategories as(String alias) {
        return new StatsCategories(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsCategories as(Name alias) {
        return new StatsCategories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatsCategories rename(String name) {
        return new StatsCategories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StatsCategories rename(Name name) {
        return new StatsCategories(name, null);
    }
}
